/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AiAgentsRouteImport } from './routes/ai-agents'
import { Route as AiImplementationRouteImport } from './routes/ai-implementation'
import { Route as AiWorkshopsRouteImport } from './routes/ai-workshops'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ConfirmedRouteImport } from './routes/confirmed'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as IndustryAutomotiveRouteImport } from './routes/industry-automotive'
import { Route as IndustryContractingRouteImport } from './routes/industry-contracting'
import { Route as IndustryElectricalRouteImport } from './routes/industry-electrical'
import { Route as IndustryHomeServicesRouteImport } from './routes/industry-home-services'
import { Route as IndustryHvacRouteImport } from './routes/industry-hvac'
import { Route as IndustryPestControlRouteImport } from './routes/industry-pest-control'
import { Route as IndustryPlumbingRouteImport } from './routes/industry-plumbing'
import { Route as IndustryRoofingRouteImport } from './routes/industry-roofing'
import { Route as IndustrySmartHomeRouteImport } from './routes/industry-smart-home'
import { Route as IndustryWindowsRouteImport } from './routes/industry-windows'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ManagedAiRouteImport } from './routes/managed-ai'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivateAiRouteImport } from './routes/private-ai'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentsRoute = AiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AiImplementationRoute = AiImplementationRouteImport.update({
  id: '/ai-implementation',
  path: '/ai-implementation',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkshopsRoute = AiWorkshopsRouteImport.update({
  id: '/ai-workshops',
  path: '/ai-workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedRoute = ConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryAutomotiveRoute = IndustryAutomotiveRouteImport.update({
  id: '/industry-automotive',
  path: '/industry-automotive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryContractingRoute = IndustryContractingRouteImport.update({
  id: '/industry-contracting',
  path: '/industry-contracting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryElectricalRoute = IndustryElectricalRouteImport.update({
  id: '/industry-electrical',
  path: '/industry-electrical',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryHomeServicesRoute = IndustryHomeServicesRouteImport.update({
  id: '/industry-home-services',
  path: '/industry-home-services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryHvacRoute = IndustryHvacRouteImport.update({
  id: '/industry-hvac',
  path: '/industry-hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryPestControlRoute = IndustryPestControlRouteImport.update({
  id: '/industry-pest-control',
  path: '/industry-pest-control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryPlumbingRoute = IndustryPlumbingRouteImport.update({
  id: '/industry-plumbing',
  path: '/industry-plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryRoofingRoute = IndustryRoofingRouteImport.update({
  id: '/industry-roofing',
  path: '/industry-roofing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySmartHomeRoute = IndustrySmartHomeRouteImport.update({
  id: '/industry-smart-home',
  path: '/industry-smart-home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryWindowsRoute = IndustryWindowsRouteImport.update({
  id: '/industry-windows',
  path: '/industry-windows',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagedAiRoute = ManagedAiRouteImport.update({
  id: '/managed-ai',
  path: '/managed-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAiRoute = PrivateAiRouteImport.update({
  id: '/private-ai',
  path: '/private-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-agents': typeof AiAgentsRoute
  '/ai-implementation': typeof AiImplementationRoute
  '/ai-workshops': typeof AiWorkshopsRoute
  '/audit': typeof AuditRoute
  '/brand-kit': typeof BrandKitRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/confirmed': typeof ConfirmedRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/industry-automotive': typeof IndustryAutomotiveRoute
  '/industry-contracting': typeof IndustryContractingRoute
  '/industry-electrical': typeof IndustryElectricalRoute
  '/industry-home-services': typeof IndustryHomeServicesRoute
  '/industry-hvac': typeof IndustryHvacRoute
  '/industry-pest-control': typeof IndustryPestControlRoute
  '/industry-plumbing': typeof IndustryPlumbingRoute
  '/industry-roofing': typeof IndustryRoofingRoute
  '/industry-smart-home': typeof IndustrySmartHomeRoute
  '/industry-windows': typeof IndustryWindowsRoute
  '/integrations': typeof IntegrationsRoute
  '/managed-ai': typeof ManagedAiRoute
  '/privacy': typeof PrivacyRoute
  '/private-ai': typeof PrivateAiRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/terms': typeof TermsRoute
  '/thanks': typeof ThanksRoute
  '/trust': typeof TrustRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-agents': typeof AiAgentsRoute
  '/ai-implementation': typeof AiImplementationRoute
  '/ai-workshops': typeof AiWorkshopsRoute
  '/audit': typeof AuditRoute
  '/brand-kit': typeof BrandKitRoute
  '/confirmed': typeof ConfirmedRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/industry-automotive': typeof IndustryAutomotiveRoute
  '/industry-contracting': typeof IndustryContractingRoute
  '/industry-electrical': typeof IndustryElectricalRoute
  '/industry-home-services': typeof IndustryHomeServicesRoute
  '/industry-hvac': typeof IndustryHvacRoute
  '/industry-pest-control': typeof IndustryPestControlRoute
  '/industry-plumbing': typeof IndustryPlumbingRoute
  '/industry-roofing': typeof IndustryRoofingRoute
  '/industry-smart-home': typeof IndustrySmartHomeRoute
  '/industry-windows': typeof IndustryWindowsRoute
  '/integrations': typeof IntegrationsRoute
  '/managed-ai': typeof ManagedAiRoute
  '/privacy': typeof PrivacyRoute
  '/private-ai': typeof PrivateAiRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/terms': typeof TermsRoute
  '/thanks': typeof ThanksRoute
  '/trust': typeof TrustRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/industries': typeof IndustriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-agents': typeof AiAgentsRoute
  '/ai-implementation': typeof AiImplementationRoute
  '/ai-workshops': typeof AiWorkshopsRoute
  '/audit': typeof AuditRoute
  '/brand-kit': typeof BrandKitRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/confirmed': typeof ConfirmedRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/industry-automotive': typeof IndustryAutomotiveRoute
  '/industry-contracting': typeof IndustryContractingRoute
  '/industry-electrical': typeof IndustryElectricalRoute
  '/industry-home-services': typeof IndustryHomeServicesRoute
  '/industry-hvac': typeof IndustryHvacRoute
  '/industry-pest-control': typeof IndustryPestControlRoute
  '/industry-plumbing': typeof IndustryPlumbingRoute
  '/industry-roofing': typeof IndustryRoofingRoute
  '/industry-smart-home': typeof IndustrySmartHomeRoute
  '/industry-windows': typeof IndustryWindowsRoute
  '/integrations': typeof IntegrationsRoute
  '/managed-ai': typeof ManagedAiRoute
  '/privacy': typeof PrivacyRoute
  '/private-ai': typeof PrivateAiRoute
  '/resources': typeof ResourcesRoute
  '/schedule': typeof ScheduleRoute
  '/terms': typeof TermsRoute
  '/thanks': typeof ThanksRoute
  '/trust': typeof TrustRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/ai-agents'
    | '/ai-implementation'
    | '/ai-workshops'
    | '/audit'
    | '/brand-kit'
    | '/case-studies'
    | '/confirmed'
    | '/contact'
    | '/how-we-work'
    | '/industries'
    | '/industry-automotive'
    | '/industry-contracting'
    | '/industry-electrical'
    | '/industry-home-services'
    | '/industry-hvac'
    | '/industry-pest-control'
    | '/industry-plumbing'
    | '/industry-roofing'
    | '/industry-smart-home'
    | '/industry-windows'
    | '/integrations'
    | '/managed-ai'
    | '/privacy'
    | '/private-ai'
    | '/resources'
    | '/schedule'
    | '/terms'
    | '/thanks'
    | '/trust'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/case-studies/'
    | '/industries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/ai-agents'
    | '/ai-implementation'
    | '/ai-workshops'
    | '/audit'
    | '/brand-kit'
    | '/confirmed'
    | '/contact'
    | '/how-we-work'
    | '/industry-automotive'
    | '/industry-contracting'
    | '/industry-electrical'
    | '/industry-home-services'
    | '/industry-hvac'
    | '/industry-pest-control'
    | '/industry-plumbing'
    | '/industry-roofing'
    | '/industry-smart-home'
    | '/industry-windows'
    | '/integrations'
    | '/managed-ai'
    | '/privacy'
    | '/private-ai'
    | '/resources'
    | '/schedule'
    | '/terms'
    | '/thanks'
    | '/trust'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/case-studies'
    | '/industries'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/ai-agents'
    | '/ai-implementation'
    | '/ai-workshops'
    | '/audit'
    | '/brand-kit'
    | '/case-studies'
    | '/confirmed'
    | '/contact'
    | '/how-we-work'
    | '/industries'
    | '/industry-automotive'
    | '/industry-contracting'
    | '/industry-electrical'
    | '/industry-home-services'
    | '/industry-hvac'
    | '/industry-pest-control'
    | '/industry-plumbing'
    | '/industry-roofing'
    | '/industry-smart-home'
    | '/industry-windows'
    | '/integrations'
    | '/managed-ai'
    | '/privacy'
    | '/private-ai'
    | '/resources'
    | '/schedule'
    | '/terms'
    | '/thanks'
    | '/trust'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/case-studies/'
    | '/industries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AiAgentsRoute: typeof AiAgentsRoute
  AiImplementationRoute: typeof AiImplementationRoute
  AiWorkshopsRoute: typeof AiWorkshopsRoute
  AuditRoute: typeof AuditRoute
  BrandKitRoute: typeof BrandKitRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ConfirmedRoute: typeof ConfirmedRoute
  ContactRoute: typeof ContactRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  IndustryAutomotiveRoute: typeof IndustryAutomotiveRoute
  IndustryContractingRoute: typeof IndustryContractingRoute
  IndustryElectricalRoute: typeof IndustryElectricalRoute
  IndustryHomeServicesRoute: typeof IndustryHomeServicesRoute
  IndustryHvacRoute: typeof IndustryHvacRoute
  IndustryPestControlRoute: typeof IndustryPestControlRoute
  IndustryPlumbingRoute: typeof IndustryPlumbingRoute
  IndustryRoofingRoute: typeof IndustryRoofingRoute
  IndustrySmartHomeRoute: typeof IndustrySmartHomeRoute
  IndustryWindowsRoute: typeof IndustryWindowsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  ManagedAiRoute: typeof ManagedAiRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivateAiRoute: typeof PrivateAiRoute
  ResourcesRoute: typeof ResourcesRoute
  ScheduleRoute: typeof ScheduleRoute
  TermsRoute: typeof TermsRoute
  ThanksRoute: typeof ThanksRoute
  TrustRoute: typeof TrustRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agents': {
      id: '/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-implementation': {
      id: '/ai-implementation'
      path: '/ai-implementation'
      fullPath: '/ai-implementation'
      preLoaderRoute: typeof AiImplementationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workshops': {
      id: '/ai-workshops'
      path: '/ai-workshops'
      fullPath: '/ai-workshops'
      preLoaderRoute: typeof AiWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed': {
      id: '/confirmed'
      path: '/confirmed'
      fullPath: '/confirmed'
      preLoaderRoute: typeof ConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-automotive': {
      id: '/industry-automotive'
      path: '/industry-automotive'
      fullPath: '/industry-automotive'
      preLoaderRoute: typeof IndustryAutomotiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-contracting': {
      id: '/industry-contracting'
      path: '/industry-contracting'
      fullPath: '/industry-contracting'
      preLoaderRoute: typeof IndustryContractingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-electrical': {
      id: '/industry-electrical'
      path: '/industry-electrical'
      fullPath: '/industry-electrical'
      preLoaderRoute: typeof IndustryElectricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-home-services': {
      id: '/industry-home-services'
      path: '/industry-home-services'
      fullPath: '/industry-home-services'
      preLoaderRoute: typeof IndustryHomeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-hvac': {
      id: '/industry-hvac'
      path: '/industry-hvac'
      fullPath: '/industry-hvac'
      preLoaderRoute: typeof IndustryHvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-pest-control': {
      id: '/industry-pest-control'
      path: '/industry-pest-control'
      fullPath: '/industry-pest-control'
      preLoaderRoute: typeof IndustryPestControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-plumbing': {
      id: '/industry-plumbing'
      path: '/industry-plumbing'
      fullPath: '/industry-plumbing'
      preLoaderRoute: typeof IndustryPlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-roofing': {
      id: '/industry-roofing'
      path: '/industry-roofing'
      fullPath: '/industry-roofing'
      preLoaderRoute: typeof IndustryRoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-smart-home': {
      id: '/industry-smart-home'
      path: '/industry-smart-home'
      fullPath: '/industry-smart-home'
      preLoaderRoute: typeof IndustrySmartHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-windows': {
      id: '/industry-windows'
      path: '/industry-windows'
      fullPath: '/industry-windows'
      preLoaderRoute: typeof IndustryWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managed-ai': {
      id: '/managed-ai'
      path: '/managed-ai'
      fullPath: '/managed-ai'
      preLoaderRoute: typeof ManagedAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-ai': {
      id: '/private-ai'
      path: '/private-ai'
      fullPath: '/private-ai'
      preLoaderRoute: typeof PrivateAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof IndustriesRoute
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface IndustriesRouteChildren {
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesSlugRoute: IndustriesSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AiAgentsRoute: AiAgentsRoute,
  AiImplementationRoute: AiImplementationRoute,
  AiWorkshopsRoute: AiWorkshopsRoute,
  AuditRoute: AuditRoute,
  BrandKitRoute: BrandKitRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ConfirmedRoute: ConfirmedRoute,
  ContactRoute: ContactRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  IndustryAutomotiveRoute: IndustryAutomotiveRoute,
  IndustryContractingRoute: IndustryContractingRoute,
  IndustryElectricalRoute: IndustryElectricalRoute,
  IndustryHomeServicesRoute: IndustryHomeServicesRoute,
  IndustryHvacRoute: IndustryHvacRoute,
  IndustryPestControlRoute: IndustryPestControlRoute,
  IndustryPlumbingRoute: IndustryPlumbingRoute,
  IndustryRoofingRoute: IndustryRoofingRoute,
  IndustrySmartHomeRoute: IndustrySmartHomeRoute,
  IndustryWindowsRoute: IndustryWindowsRoute,
  IntegrationsRoute: IntegrationsRoute,
  ManagedAiRoute: ManagedAiRoute,
  PrivacyRoute: PrivacyRoute,
  PrivateAiRoute: PrivateAiRoute,
  ResourcesRoute: ResourcesRoute,
  ScheduleRoute: ScheduleRoute,
  TermsRoute: TermsRoute,
  ThanksRoute: ThanksRoute,
  TrustRoute: TrustRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
