/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AiAgentsRouteImport } from './routes/ai-agents'
import { Route as AiEnablementRouteImport } from './routes/ai-enablement'
import { Route as AiImplementationRouteImport } from './routes/ai-implementation'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BookACallRouteImport } from './routes/book-a-call'
import { Route as BusinessSystemsDevelopmentRouteImport } from './routes/business-systems-development'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CyberSecurityRouteImport } from './routes/cyber-security'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as IndustryAutomotiveRouteImport } from './routes/industry-automotive'
import { Route as IndustryContractingRouteImport } from './routes/industry-contracting'
import { Route as IndustryElectricalRouteImport } from './routes/industry-electrical'
import { Route as IndustryFinancialServicesRouteImport } from './routes/industry-financial-services'
import { Route as IndustryHomeServicesRouteImport } from './routes/industry-home-services'
import { Route as IndustryHvacRouteImport } from './routes/industry-hvac'
import { Route as IndustryLogisticsRouteImport } from './routes/industry-logistics'
import { Route as IndustryManufacturingRouteImport } from './routes/industry-manufacturing'
import { Route as IndustryMarketingRouteImport } from './routes/industry-marketing'
import { Route as IndustryPestControlRouteImport } from './routes/industry-pest-control'
import { Route as IndustryPlumbingRouteImport } from './routes/industry-plumbing'
import { Route as IndustryProfessionalServicesRouteImport } from './routes/industry-professional-services'
import { Route as IndustryRecruitingRouteImport } from './routes/industry-recruiting'
import { Route as IndustryRoofingRouteImport } from './routes/industry-roofing'
import { Route as IndustrySmartHomeRouteImport } from './routes/industry-smart-home'
import { Route as IndustryWindowsRouteImport } from './routes/industry-windows'
import { Route as ManagedAiRouteImport } from './routes/managed-ai'
import { Route as OpsConsultingRouteImport } from './routes/ops-consulting'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivateAiRouteImport } from './routes/private-ai'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as PodcastSlugRouteImport } from './routes/podcast.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentsRoute = AiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEnablementRoute = AiEnablementRouteImport.update({
  id: '/ai-enablement',
  path: '/ai-enablement',
  getParentRoute: () => rootRouteImport,
} as any)
const AiImplementationRoute = AiImplementationRouteImport.update({
  id: '/ai-implementation',
  path: '/ai-implementation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BookACallRoute = BookACallRouteImport.update({
  id: '/book-a-call',
  path: '/book-a-call',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSystemsDevelopmentRoute =
  BusinessSystemsDevelopmentRouteImport.update({
    id: '/business-systems-development',
    path: '/business-systems-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberSecurityRoute = CyberSecurityRouteImport.update({
  id: '/cyber-security',
  path: '/cyber-security',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryAutomotiveRoute = IndustryAutomotiveRouteImport.update({
  id: '/industry-automotive',
  path: '/industry-automotive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryContractingRoute = IndustryContractingRouteImport.update({
  id: '/industry-contracting',
  path: '/industry-contracting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryElectricalRoute = IndustryElectricalRouteImport.update({
  id: '/industry-electrical',
  path: '/industry-electrical',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryFinancialServicesRoute =
  IndustryFinancialServicesRouteImport.update({
    id: '/industry-financial-services',
    path: '/industry-financial-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustryHomeServicesRoute = IndustryHomeServicesRouteImport.update({
  id: '/industry-home-services',
  path: '/industry-home-services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryHvacRoute = IndustryHvacRouteImport.update({
  id: '/industry-hvac',
  path: '/industry-hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryLogisticsRoute = IndustryLogisticsRouteImport.update({
  id: '/industry-logistics',
  path: '/industry-logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryManufacturingRoute = IndustryManufacturingRouteImport.update({
  id: '/industry-manufacturing',
  path: '/industry-manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryMarketingRoute = IndustryMarketingRouteImport.update({
  id: '/industry-marketing',
  path: '/industry-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryPestControlRoute = IndustryPestControlRouteImport.update({
  id: '/industry-pest-control',
  path: '/industry-pest-control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryPlumbingRoute = IndustryPlumbingRouteImport.update({
  id: '/industry-plumbing',
  path: '/industry-plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryProfessionalServicesRoute =
  IndustryProfessionalServicesRouteImport.update({
    id: '/industry-professional-services',
    path: '/industry-professional-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustryRecruitingRoute = IndustryRecruitingRouteImport.update({
  id: '/industry-recruiting',
  path: '/industry-recruiting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryRoofingRoute = IndustryRoofingRouteImport.update({
  id: '/industry-roofing',
  path: '/industry-roofing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySmartHomeRoute = IndustrySmartHomeRouteImport.update({
  id: '/industry-smart-home',
  path: '/industry-smart-home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryWindowsRoute = IndustryWindowsRouteImport.update({
  id: '/industry-windows',
  path: '/industry-windows',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagedAiRoute = ManagedAiRouteImport.update({
  id: '/managed-ai',
  path: '/managed-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsConsultingRoute = OpsConsultingRouteImport.update({
  id: '/ops-consulting',
  path: '/ops-consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAiRoute = PrivateAiRouteImport.update({
  id: '/private-ai',
  path: '/private-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const PodcastSlugRoute = PodcastSlugRouteImport.update({
  id: '/podcast/$slug',
  path: '/podcast/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-agents': typeof AiAgentsRoute
  '/ai-enablement': typeof AiEnablementRoute
  '/ai-implementation': typeof AiImplementationRoute
  '/audit': typeof AuditRoute
  '/book-a-call': typeof BookACallRoute
  '/business-systems-development': typeof BusinessSystemsDevelopmentRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/cyber-security': typeof CyberSecurityRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/industries': typeof IndustriesRoute
  '/industry-automotive': typeof IndustryAutomotiveRoute
  '/industry-contracting': typeof IndustryContractingRoute
  '/industry-electrical': typeof IndustryElectricalRoute
  '/industry-financial-services': typeof IndustryFinancialServicesRoute
  '/industry-home-services': typeof IndustryHomeServicesRoute
  '/industry-hvac': typeof IndustryHvacRoute
  '/industry-logistics': typeof IndustryLogisticsRoute
  '/industry-manufacturing': typeof IndustryManufacturingRoute
  '/industry-marketing': typeof IndustryMarketingRoute
  '/industry-pest-control': typeof IndustryPestControlRoute
  '/industry-plumbing': typeof IndustryPlumbingRoute
  '/industry-professional-services': typeof IndustryProfessionalServicesRoute
  '/industry-recruiting': typeof IndustryRecruitingRoute
  '/industry-roofing': typeof IndustryRoofingRoute
  '/industry-smart-home': typeof IndustrySmartHomeRoute
  '/industry-windows': typeof IndustryWindowsRoute
  '/managed-ai': typeof ManagedAiRoute
  '/ops-consulting': typeof OpsConsultingRoute
  '/privacy': typeof PrivacyRoute
  '/private-ai': typeof PrivateAiRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-agents': typeof AiAgentsRoute
  '/ai-enablement': typeof AiEnablementRoute
  '/ai-implementation': typeof AiImplementationRoute
  '/audit': typeof AuditRoute
  '/book-a-call': typeof BookACallRoute
  '/business-systems-development': typeof BusinessSystemsDevelopmentRoute
  '/cyber-security': typeof CyberSecurityRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/industries': typeof IndustriesRoute
  '/industry-automotive': typeof IndustryAutomotiveRoute
  '/industry-contracting': typeof IndustryContractingRoute
  '/industry-electrical': typeof IndustryElectricalRoute
  '/industry-financial-services': typeof IndustryFinancialServicesRoute
  '/industry-home-services': typeof IndustryHomeServicesRoute
  '/industry-hvac': typeof IndustryHvacRoute
  '/industry-logistics': typeof IndustryLogisticsRoute
  '/industry-manufacturing': typeof IndustryManufacturingRoute
  '/industry-marketing': typeof IndustryMarketingRoute
  '/industry-pest-control': typeof IndustryPestControlRoute
  '/industry-plumbing': typeof IndustryPlumbingRoute
  '/industry-professional-services': typeof IndustryProfessionalServicesRoute
  '/industry-recruiting': typeof IndustryRecruitingRoute
  '/industry-roofing': typeof IndustryRoofingRoute
  '/industry-smart-home': typeof IndustrySmartHomeRoute
  '/industry-windows': typeof IndustryWindowsRoute
  '/managed-ai': typeof ManagedAiRoute
  '/ops-consulting': typeof OpsConsultingRoute
  '/privacy': typeof PrivacyRoute
  '/private-ai': typeof PrivateAiRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/case-studies': typeof CaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai-agents': typeof AiAgentsRoute
  '/ai-enablement': typeof AiEnablementRoute
  '/ai-implementation': typeof AiImplementationRoute
  '/audit': typeof AuditRoute
  '/book-a-call': typeof BookACallRoute
  '/business-systems-development': typeof BusinessSystemsDevelopmentRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/cyber-security': typeof CyberSecurityRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/industries': typeof IndustriesRoute
  '/industry-automotive': typeof IndustryAutomotiveRoute
  '/industry-contracting': typeof IndustryContractingRoute
  '/industry-electrical': typeof IndustryElectricalRoute
  '/industry-financial-services': typeof IndustryFinancialServicesRoute
  '/industry-home-services': typeof IndustryHomeServicesRoute
  '/industry-hvac': typeof IndustryHvacRoute
  '/industry-logistics': typeof IndustryLogisticsRoute
  '/industry-manufacturing': typeof IndustryManufacturingRoute
  '/industry-marketing': typeof IndustryMarketingRoute
  '/industry-pest-control': typeof IndustryPestControlRoute
  '/industry-plumbing': typeof IndustryPlumbingRoute
  '/industry-professional-services': typeof IndustryProfessionalServicesRoute
  '/industry-recruiting': typeof IndustryRecruitingRoute
  '/industry-roofing': typeof IndustryRoofingRoute
  '/industry-smart-home': typeof IndustrySmartHomeRoute
  '/industry-windows': typeof IndustryWindowsRoute
  '/managed-ai': typeof ManagedAiRoute
  '/ops-consulting': typeof OpsConsultingRoute
  '/privacy': typeof PrivacyRoute
  '/private-ai': typeof PrivateAiRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/ai-agents'
    | '/ai-enablement'
    | '/ai-implementation'
    | '/audit'
    | '/book-a-call'
    | '/business-systems-development'
    | '/case-studies'
    | '/cyber-security'
    | '/how-we-work'
    | '/industries'
    | '/industry-automotive'
    | '/industry-contracting'
    | '/industry-electrical'
    | '/industry-financial-services'
    | '/industry-home-services'
    | '/industry-hvac'
    | '/industry-logistics'
    | '/industry-manufacturing'
    | '/industry-marketing'
    | '/industry-pest-control'
    | '/industry-plumbing'
    | '/industry-professional-services'
    | '/industry-recruiting'
    | '/industry-roofing'
    | '/industry-smart-home'
    | '/industry-windows'
    | '/managed-ai'
    | '/ops-consulting'
    | '/privacy'
    | '/private-ai'
    | '/resources'
    | '/terms'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/podcast/$slug'
    | '/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/ai-agents'
    | '/ai-enablement'
    | '/ai-implementation'
    | '/audit'
    | '/book-a-call'
    | '/business-systems-development'
    | '/cyber-security'
    | '/how-we-work'
    | '/industries'
    | '/industry-automotive'
    | '/industry-contracting'
    | '/industry-electrical'
    | '/industry-financial-services'
    | '/industry-home-services'
    | '/industry-hvac'
    | '/industry-logistics'
    | '/industry-manufacturing'
    | '/industry-marketing'
    | '/industry-pest-control'
    | '/industry-plumbing'
    | '/industry-professional-services'
    | '/industry-recruiting'
    | '/industry-roofing'
    | '/industry-smart-home'
    | '/industry-windows'
    | '/managed-ai'
    | '/ops-consulting'
    | '/privacy'
    | '/private-ai'
    | '/resources'
    | '/terms'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/podcast/$slug'
    | '/case-studies'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/ai-agents'
    | '/ai-enablement'
    | '/ai-implementation'
    | '/audit'
    | '/book-a-call'
    | '/business-systems-development'
    | '/case-studies'
    | '/cyber-security'
    | '/how-we-work'
    | '/industries'
    | '/industry-automotive'
    | '/industry-contracting'
    | '/industry-electrical'
    | '/industry-financial-services'
    | '/industry-home-services'
    | '/industry-hvac'
    | '/industry-logistics'
    | '/industry-manufacturing'
    | '/industry-marketing'
    | '/industry-pest-control'
    | '/industry-plumbing'
    | '/industry-professional-services'
    | '/industry-recruiting'
    | '/industry-roofing'
    | '/industry-smart-home'
    | '/industry-windows'
    | '/managed-ai'
    | '/ops-consulting'
    | '/privacy'
    | '/private-ai'
    | '/resources'
    | '/terms'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/podcast/$slug'
    | '/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AiAgentsRoute: typeof AiAgentsRoute
  AiEnablementRoute: typeof AiEnablementRoute
  AiImplementationRoute: typeof AiImplementationRoute
  AuditRoute: typeof AuditRoute
  BookACallRoute: typeof BookACallRoute
  BusinessSystemsDevelopmentRoute: typeof BusinessSystemsDevelopmentRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  CyberSecurityRoute: typeof CyberSecurityRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  IndustriesRoute: typeof IndustriesRoute
  IndustryAutomotiveRoute: typeof IndustryAutomotiveRoute
  IndustryContractingRoute: typeof IndustryContractingRoute
  IndustryElectricalRoute: typeof IndustryElectricalRoute
  IndustryFinancialServicesRoute: typeof IndustryFinancialServicesRoute
  IndustryHomeServicesRoute: typeof IndustryHomeServicesRoute
  IndustryHvacRoute: typeof IndustryHvacRoute
  IndustryLogisticsRoute: typeof IndustryLogisticsRoute
  IndustryManufacturingRoute: typeof IndustryManufacturingRoute
  IndustryMarketingRoute: typeof IndustryMarketingRoute
  IndustryPestControlRoute: typeof IndustryPestControlRoute
  IndustryPlumbingRoute: typeof IndustryPlumbingRoute
  IndustryProfessionalServicesRoute: typeof IndustryProfessionalServicesRoute
  IndustryRecruitingRoute: typeof IndustryRecruitingRoute
  IndustryRoofingRoute: typeof IndustryRoofingRoute
  IndustrySmartHomeRoute: typeof IndustrySmartHomeRoute
  IndustryWindowsRoute: typeof IndustryWindowsRoute
  ManagedAiRoute: typeof ManagedAiRoute
  OpsConsultingRoute: typeof OpsConsultingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivateAiRoute: typeof PrivateAiRoute
  ResourcesRoute: typeof ResourcesRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PodcastSlugRoute: typeof PodcastSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agents': {
      id: '/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-enablement': {
      id: '/ai-enablement'
      path: '/ai-enablement'
      fullPath: '/ai-enablement'
      preLoaderRoute: typeof AiEnablementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-implementation': {
      id: '/ai-implementation'
      path: '/ai-implementation'
      fullPath: '/ai-implementation'
      preLoaderRoute: typeof AiImplementationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-call': {
      id: '/book-a-call'
      path: '/book-a-call'
      fullPath: '/book-a-call'
      preLoaderRoute: typeof BookACallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-systems-development': {
      id: '/business-systems-development'
      path: '/business-systems-development'
      fullPath: '/business-systems-development'
      preLoaderRoute: typeof BusinessSystemsDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-security': {
      id: '/cyber-security'
      path: '/cyber-security'
      fullPath: '/cyber-security'
      preLoaderRoute: typeof CyberSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-automotive': {
      id: '/industry-automotive'
      path: '/industry-automotive'
      fullPath: '/industry-automotive'
      preLoaderRoute: typeof IndustryAutomotiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-contracting': {
      id: '/industry-contracting'
      path: '/industry-contracting'
      fullPath: '/industry-contracting'
      preLoaderRoute: typeof IndustryContractingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-electrical': {
      id: '/industry-electrical'
      path: '/industry-electrical'
      fullPath: '/industry-electrical'
      preLoaderRoute: typeof IndustryElectricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-financial-services': {
      id: '/industry-financial-services'
      path: '/industry-financial-services'
      fullPath: '/industry-financial-services'
      preLoaderRoute: typeof IndustryFinancialServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-home-services': {
      id: '/industry-home-services'
      path: '/industry-home-services'
      fullPath: '/industry-home-services'
      preLoaderRoute: typeof IndustryHomeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-hvac': {
      id: '/industry-hvac'
      path: '/industry-hvac'
      fullPath: '/industry-hvac'
      preLoaderRoute: typeof IndustryHvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-logistics': {
      id: '/industry-logistics'
      path: '/industry-logistics'
      fullPath: '/industry-logistics'
      preLoaderRoute: typeof IndustryLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-manufacturing': {
      id: '/industry-manufacturing'
      path: '/industry-manufacturing'
      fullPath: '/industry-manufacturing'
      preLoaderRoute: typeof IndustryManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-marketing': {
      id: '/industry-marketing'
      path: '/industry-marketing'
      fullPath: '/industry-marketing'
      preLoaderRoute: typeof IndustryMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-pest-control': {
      id: '/industry-pest-control'
      path: '/industry-pest-control'
      fullPath: '/industry-pest-control'
      preLoaderRoute: typeof IndustryPestControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-plumbing': {
      id: '/industry-plumbing'
      path: '/industry-plumbing'
      fullPath: '/industry-plumbing'
      preLoaderRoute: typeof IndustryPlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-professional-services': {
      id: '/industry-professional-services'
      path: '/industry-professional-services'
      fullPath: '/industry-professional-services'
      preLoaderRoute: typeof IndustryProfessionalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-recruiting': {
      id: '/industry-recruiting'
      path: '/industry-recruiting'
      fullPath: '/industry-recruiting'
      preLoaderRoute: typeof IndustryRecruitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-roofing': {
      id: '/industry-roofing'
      path: '/industry-roofing'
      fullPath: '/industry-roofing'
      preLoaderRoute: typeof IndustryRoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-smart-home': {
      id: '/industry-smart-home'
      path: '/industry-smart-home'
      fullPath: '/industry-smart-home'
      preLoaderRoute: typeof IndustrySmartHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-windows': {
      id: '/industry-windows'
      path: '/industry-windows'
      fullPath: '/industry-windows'
      preLoaderRoute: typeof IndustryWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managed-ai': {
      id: '/managed-ai'
      path: '/managed-ai'
      fullPath: '/managed-ai'
      preLoaderRoute: typeof ManagedAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-consulting': {
      id: '/ops-consulting'
      path: '/ops-consulting'
      fullPath: '/ops-consulting'
      preLoaderRoute: typeof OpsConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-ai': {
      id: '/private-ai'
      path: '/private-ai'
      fullPath: '/private-ai'
      preLoaderRoute: typeof PrivateAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/podcast/$slug': {
      id: '/podcast/$slug'
      path: '/podcast/$slug'
      fullPath: '/podcast/$slug'
      preLoaderRoute: typeof PodcastSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AiAgentsRoute: AiAgentsRoute,
  AiEnablementRoute: AiEnablementRoute,
  AiImplementationRoute: AiImplementationRoute,
  AuditRoute: AuditRoute,
  BookACallRoute: BookACallRoute,
  BusinessSystemsDevelopmentRoute: BusinessSystemsDevelopmentRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  CyberSecurityRoute: CyberSecurityRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  IndustriesRoute: IndustriesRoute,
  IndustryAutomotiveRoute: IndustryAutomotiveRoute,
  IndustryContractingRoute: IndustryContractingRoute,
  IndustryElectricalRoute: IndustryElectricalRoute,
  IndustryFinancialServicesRoute: IndustryFinancialServicesRoute,
  IndustryHomeServicesRoute: IndustryHomeServicesRoute,
  IndustryHvacRoute: IndustryHvacRoute,
  IndustryLogisticsRoute: IndustryLogisticsRoute,
  IndustryManufacturingRoute: IndustryManufacturingRoute,
  IndustryMarketingRoute: IndustryMarketingRoute,
  IndustryPestControlRoute: IndustryPestControlRoute,
  IndustryPlumbingRoute: IndustryPlumbingRoute,
  IndustryProfessionalServicesRoute: IndustryProfessionalServicesRoute,
  IndustryRecruitingRoute: IndustryRecruitingRoute,
  IndustryRoofingRoute: IndustryRoofingRoute,
  IndustrySmartHomeRoute: IndustrySmartHomeRoute,
  IndustryWindowsRoute: IndustryWindowsRoute,
  ManagedAiRoute: ManagedAiRoute,
  OpsConsultingRoute: OpsConsultingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivateAiRoute: PrivateAiRoute,
  ResourcesRoute: ResourcesRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  PodcastSlugRoute: PodcastSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
